[build]
  command = "hugo --gc --minify -b $URL"
  publish = "public"

[build.environment]
  HUGO_VERSION = "0.80.0"
  HUGO_ENABLEGITINFO = "true"

[context.production.environment]
  HUGO_ENV = "production"

[context.deploy-preview]
  command = "hugo --gc --minify --buildFuture -b $DEPLOY_PRIME_URL"

[context.branch-deploy]
  command = "hugo --gc --minify -b $DEPLOY_PRIME_URL"
  
[[redirects]]
  from = "/apetros"
  to = "/authors/p.-aristidou"
  status = 302

[[redirects]]
  from = "/git"
  to = "https://github.com/SPS-L"
  status = 302

[[redirects]]
  from = "/pyramses"
  to = "https://pyramses.paristidou.info"
  status = 302

[[redirects]]
  from = "/post/2020_phd_position_rte/"
  to = "/post/2020_phd_position_num/"
  status = 302

[[redirects]]
  from = "/open-positions"
  to = "/categories/open-positions/"
  status = 302

[[redirects]]
  from = "/jhub"
  to = "https://vmi444960.contaboserver.net/"
  status = 302

[[redirects]]
  from = "/Nordic_JhubStart"
  to = "https://vmi444960.contaboserver.net/hub?next=%2Fuser-redirect%2Fgit-pull?repo%3Dhttps%253A%252F%252Fgithub.com%252FSPS-L%252FNordic_JhubStart%26branch%3Dmain%26urlpath%3Dlab%252Ftree%252FNordic_JhubStart%252F%253Fautodecode"
  status = 302

[[redirects]]
  from = "/jhub-nordic"
  to = "https://vmi444960.contaboserver.net/hub?next=%2Fuser-redirect%2Fgit-pull?repo%3Dhttps%253A%252F%252Fgithub.com%252FSPS-L%252FNordic_JhubStart%26branch%3Dmain%26urlpath%3Dlab%252Ftree%252FNordic_JhubStart%252F%253Fautodecode"
  status = 302
  
[[redirects]]
  from = "/jhub-sync-mach"
  to = "https://vmi444960.contaboserver.net/hub/user-redirect/git-pull?repo=https%3A%2F%2Fgithub.com%2FSPS-L%2FSync_mach_Octave&urlpath=lab%2Ftree%2FSync_mach_Octave%2F&branch=main"
  status = 302

[[redirects]]
  from = "/jhub-econ-oper"
  to = "https://vmi444960.contaboserver.net/hub?next=%2Fuser-redirect%2Fgit-pull?repo%3Dhttps%253A%252F%252Fgithub.com%252FSPS-L%252FEconomic-Operation-examples%26branch%3Dmain%26urlpath%3Dlab%252Ftree%252FEconomic-Operation-examples%252F%253Fautodecode"
  status = 302 

[[redirects]]
  from = "/jhub-5-bus"
  to = "https://vmi444960.contaboserver.net/hub/user-redirect/git-pull?repo=https%3A%2F%2Fgithub.com%2FSPS-L%2F5_bus_test_system&urlpath=lab%2Ftree%2F5_bus_test_system%2F&branch=main"
  status = 302 
